"""remove latitude longitude in order model

Revision ID: 046965a2c67e
Revises: 50852e4bee9f
Create Date: 2026-08-12 12:51:01.624282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046965a2c67e'
down_revision: Union[str, Sequence[str], None] = '50852e4bee9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receiver_latitude')
    op.drop_column('orders', 'receiver_longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receiver_longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('receiver_latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
