"""make customer profile fields nullable

Revision ID: 2c64709c938e
Revises: a23273d5b6f5
Create Date: 2026-08-08 23:23:25.805076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c64709c938e'
down_revision: Union[str, Sequence[str], None] = 'a23273d5b6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer_profiles', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('customer_profiles', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer_profiles', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
