"""remove email and map in customer model

Revision ID: 50852e4bee9f
Revises: 51bc563ac9b3
Create Date: 2026-08-12 12:22:01.168011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50852e4bee9f'
down_revision: Union[str, Sequence[str], None] = '51bc563ac9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_profiles_email'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'email')
    op.drop_column('customer_profiles', 'latitude')
    op.drop_column('customer_profiles', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_customer_profiles_email'), 'customer_profiles', ['email'], unique=True)
    # ### end Alembic commands ###
