"""add variant id to order items

Revision ID: 51bc563ac9b3
Revises: 11d4bc640b3f
Create Date: 2026-08-12 01:03:30.912992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bc563ac9b3'
down_revision: Union[str, Sequence[str], None] = '11d4bc640b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_items', 'variant_id')
    # ### end Alembic commands ###
