"""update schema

Revision ID: 52cf30e392a7
Revises: 9321b201e655
Create Date: 2026-06-24 07:45:12.677318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cf30e392a7'
down_revision: Union[str, Sequence[str], None] = '9321b201e655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('bale', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('eita', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('rubika', sa.String(), nullable=True))
    op.drop_column('stores', 'logo')
    op.drop_column('stores', 'lat')
    op.drop_column('stores', 'name')
    op.drop_column('stores', 'lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stores', 'rubika')
    op.drop_column('stores', 'eita')
    op.drop_column('stores', 'bale')
    # ### end Alembic commands ###
