"""update applicationID

Revision ID: 5d3404cf2038
Revises: b781e9eebe94
Create Date: 2026-06-12 18:12:00.468258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3404cf2038'
down_revision: Union[str, Sequence[str], None] = 'b781e9eebe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
