"""update applicationID

Revision ID: 5f6a6cadb209
Revises: 5d3404cf2038
Create Date: 2026-06-12 18:12:46.516671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6a6cadb209'
down_revision: Union[str, Sequence[str], None] = '5d3404cf2038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_application_id'), table_name='users')
    op.create_index(op.f('ix_users_application_id'), 'users', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_application_id'), table_name='users')
    op.create_index(op.f('ix_users_application_id'), 'users', ['application_id'], unique=False)
    # ### end Alembic commands ###
