"""add is_packaged to products

Revision ID: 9add62fe988c
Revises: 0db0124619fb
Create Date: 2026-07-21 08:19:15.046081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9add62fe988c'
down_revision: Union[str, Sequence[str], None] = '0db0124619fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_packaged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_packaged')
    # ### end Alembic commands ###
