"""set applicationID

Revision ID: b781e9eebe94
Revises: 59e4a7f51876
Create Date: 2026-06-12 18:08:07.559519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b781e9eebe94'
down_revision: Union[str, Sequence[str], None] = '59e4a7f51876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_application_id'), 'categories', ['application_id'], unique=False)
    op.add_column('stores', sa.Column('application_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_application_id'), 'users', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_application_id'), table_name='users')
    op.drop_column('users', 'application_id')
    op.drop_column('stores', 'application_id')
    op.drop_index(op.f('ix_categories_application_id'), table_name='categories')
    op.drop_column('categories', 'application_id')
    # ### end Alembic commands ###
